### PR TITLE
Return first video for YouTube query instead of search page

### LINKED ISSUE #37: Youtube command to link to top result
It would be nice if, instead of a youtube search query, there was a youtube command to bring up a link to the top youtube search result directly, like the old bot had.

### PR DESCRIPTION
**Pull request by jangler**
Resolves #37. Current BotB bot does this, and I think it's more useful.

### CODE REVIEW

**Comment by langel** [comment]
Who's API key are we using?  Could this break in the future?

**Comment by jangler** [comment]
One of mine (mentioned in a code comment). If you want to replace it with one of yours, go ahead. I don't think there's any expiration (etc.) on them, but I'll check.

**Comment by langel** [comment]
Oh, LOL, I totally breezed over the comments.  Sounds good to me.  If it expires/breaks later we'll open a new bug ticket.

**Comment by jangler** [comment]
Yeah, Google API keys don't expire anyway, so we should be fine.

**Pull request merged**
