### PR TITLE
Levelup script rewritten & ES6 refactoring

### PR DESCRIPTION
**Pull request by Savestate2A03**
the new script should fix most edge cases, and gets rid of the 'more points than the levelup threshold' bug. (example: !levelup coda give a few months instead of < 1 day)

in the event a new edge case pops up, it shouldn't be too hard to implement with the current structure of the function

### CODE REVIEW

**Comment by Savestate2A03** [comment]
Just finished refactoring ! 
afaik I didn't make any logic changes, just rewrote a lot of the bot with ES6 compliant code

**Comment by jangler** [comment]
Apparently JS became Ruby while I wasn't looking!

FWIW, I don't like to commit a lot of inconsequential alterations (like the semicolon removals here) to a VCS since it breaks the blame tool.

**Comment by Savestate2A03** [comment]
i'll gladly take the blame for Anything if it means no semicolons haha

there's probably more I could do, but for this I focused mostly expression/statement bodies rewritten w/ arrow notation, blockquote ${stuff}, and removing semicolons

**Comment by jangler** [comment]
Also breaks automatic merge for any concurrent changes by other people ;(

**Comment by Savestate2A03** [comment]
Hmm, I could wait until everyone finishes with their current changes, fix things up on my end, and submit another pull request. I just noticed my IDE was mixing tabs and spaces anyways so I need to go back and fix those

**Comment by Savestate2A03** [comment]
One way or another my goal is to get rid of the semicolon in this project

**Pull request closed without merging**
