### PR TITLE
Echo bot messages to console

### LINKED ISSUE #55: add bot output to stdout
right now if you are watching node's output in the terminal you can see what everyone says but not what the bot says

### PR DESCRIPTION
**Pull request by jangler**
Resolves #55.

This implementation includes the color text, which I personally think is good, but you could argue that it's better to ignore it on the basis of having clean output.

### CODE REVIEW

**Comment by langel** [comment]
The colors are not working in my terminal.  The escape character might be doing what it's supposed to, but the I just get the color, color integers.  There's always https://www.npmjs.com/package/colors

Or just put the console.log above the color code (ap|pre)pending text line. _shrugs_

**Comment by jangler** [comment]
Yes, I didn't mean that the colors would work in the console, just that the codes would appear. Colorizing output might get ugly in logs if output is teed to a file.

But yes, I initially put the `console.log` above the previous line, and that obviously works fine too.

**Comment by jangler** [comment]
IMO it should do the same thing as it does when it receives a message with IRC color codes.

**Comment by langel** [comment]
Alright, I'm cool with this.  Merging!

**Pull request merged**
