### PR TITLE
ES6ified + Fixed 'days_to_fulldate' Function

### PR DESCRIPTION
**Pull request by Savestate2A03**
Ok! Take 2...

I was looking at the [Network Graph](https://github.com/langel/botb_irc_bot/network), and as far as I can tell, it looks like everyone is caught up with it (sans sleeparrow, whose fork was [already implemented](https://github.com/langel/botb_irc_bot/commit/505fb79070f8c27c8111a57ae6744f05a8bef8e7))

Now would be the time to merge, and from there to continue the bot development with ES6 in mind.

### CODE REVIEW

**Comment by jangler** [comment]
I have node v6.7.0 and the string interpolation doesn't seem to work for me:

```
brandon@desk ~ $ node --version
v6.7.0
brandon@desk ~ $ node
> x = 4
4
> '${x}'
'${x}'
```

**Comment by Savestate2A03** [comment]
Make sure to use backticks! `console.log(`${x}`)` It looks like you're using single quotation marks

**Comment by jangler** [comment]
Ah, cool, thanks. Works for me.

**Comment by langel** [comment]
there is so much about this I find cringey
been using semicolons my whole life and now they're unnecessary?
let replaces var but did var being block scoped change?
bash CLI style back tick variable string insertion because + concatenation looks like math?
but the thing that really messes with my head are these arrow functions...
"javascript sucks because it's loosely typed"
"yeah, well at least you don't need to declare functions with the function type label now"
i seriously don't understand what is gained by this evolution other than obfuscated meaning and looking cool; people read left to right but the arrow is after the parameters; looks like a bastard ternary conditional that takes a code block for an operator
i'm late for a thing, should be back home in some hours, will try to let this all sink in

**Comment by langel** [comment]
I've had time to marinate.  Once my coworkers explained that arrow functions utilize the 'penis operator' I fell in love.  I'm still not sold on the missing semicolons.  Too tired to pull and run; will prolly do so at work tomorrow.

**Comment by langel** [comment]
Alright, I've adopted the penis operator into my lexicon.  
Still not too sure about dropping the semicolons.
They were never ES spec demanded in the first place, but I kinda like them.

**Comment by Savestate2A03** [comment]
I see removing them as just another thing to not worry about. Glad the merge worked out!

Sorry for taking all the blame Jangler.

**Pull request merged**
